import { EditorThemeClasses } from 'lexical';

export const defaultTheme: EditorThemeClasses = {
  text: {
    bold: 'lex-bold',
    italic: 'lex-italic',
    underline: 'lex-underline',
    code: 'lex-text-code',
    strikethrough: 'lex-strikethrough',
    subscript: 'lex-subscript',
    superscript: 'lex-superscript',
    underlineStrikethrough: 'lex-underlineStrikethrough',
  },
  heading: {
    h1: 'lex-h1',
    h2: 'lex-h2',
    h3: 'lex-h3',
    h4: 'lex-h4',
    h5: 'lex-h5',
    h6: 'lex-h6',
  },
  list: {
    ul: 'lex-ul',
    ulDepth: ['lex-ul-1', 'lex-ul-2', 'lex-ul-3'],
    ol: 'lex-ol',
    olDepth: ['lex-ol-1', 'lex-ol-2', 'lex-ol-3'],
    checklist: 'lex-checklist',
    listitem: 'lex-listitem',
    listitemChecked: 'lex-listitem-checked',
    listitemUnchecked: 'lex-listitem-unchecked',
    nested: {
      list: 'lex-nested-list',
      listitem: 'lex-nested-listitem',
    },
  },
  listItem: 'lex-listitem',
  table: 'lex-table',
  tableCell: 'lex-tablecell',
  tableRow: 'lex-tablerow',
  quote: 'lex-quote',
  link: 'lex-link',
  code: 'lex-code',
  codeHighlight: {
    atrule: 'lex-tokenAttr',
    attr: 'lex-tokenAttr',
    boolean: 'lex-tokenProperty',
    builtin: 'lex-tokenSelector',
    cdata: 'lex-tokenComment',
    char: 'lex-tokenSelector',
    class: 'lex-tokenFunction',
    'class-name': 'lex-tokenFunction',
    comment: 'lex-tokenComment',
    constant: 'lex-tokenProperty',
    deleted: 'lex-tokenProperty',
    doctype: 'lex-tokenComment',
    entity: 'lex-tokenOperator',
    function: 'lex-tokenFunction',
    important: 'lex-tokenVariable',
    inserted: 'lex-tokenSelector',
    keyword: 'lex-tokenAttr',
    namespace: 'lex-tokenVariable',
    number: 'lex-tokenProperty',
    operator: 'lex-tokenOperator',
    prolog: 'lex-tokenComment',
    property: 'lex-tokenProperty',
    punctuation: 'lex-tokenPunctuation',
    regex: 'lex-tokenVariable',
    selector: 'lex-tokenSelector',
    string: 'lex-tokenSelector',
    symbol: 'lex-tokenProperty',
    tag: 'lex-tokenProperty',
    url: 'lex-tokenOperator',
    variable: 'lex-tokenVariable',
  },
};
